platform :ios ,'8.0'
target "MyTestForNewFrameWork" do
 	pod 'AFNetworking','~>3.1.0'
	pod 'Reachability','~>3.2'
	pod 'Masonry','~>1.0.0'
	pod 'SDWebImage','~>3.7.5'
	pod 'MJExtension'
    pod 'MBProgressHUD', '~> 0.9.2'
end

